{"ResponseBody":{"Message":"An item with the same key has already been added. Key: _EmailSettingDetailId","InnerMessage":null,"StackTrace":"   at BottomhalfCore.DatabaseLayer.MySql.Code.Db.GetList[T](String ProcedureName, List`1 properties, Object Parameters, Boolean OutParam) in D:\\ws\\Server\\OnlineDataBuilderServer\\BottomhalfCore\\DatabaseLayer\\MySql\\Code\\Db.cs:line 301\r\n   at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)\r\n   at BottomhalfCore.DatabaseLayer.MySql.Code.Db.Get[T](String ProcedureName, Object Parameters, Boolean OutParam) in D:\\ws\\Server\\OnlineDataBuilderServer\\BottomhalfCore\\DatabaseLayer\\MySql\\Code\\Db.cs:line 319\r\n   at EMailService.Service.EMailManager.GetDefaultEmailDetail() in D:\\ws\\Server\\OnlineDataBuilderServer\\EMailService\\Service\\EMailManager.cs:line 34\r\n   at EMailService.Service.EMailManager.ReadMails(EmailSettingDetail emailSettingDetail) in D:\\ws\\Server\\OnlineDataBuilderServer\\EMailService\\Service\\EMailManager.cs:line 146\r\n   at OnlineDataBuilder.Controllers.WeatherForecastController.Get() in D:\\ws\\Server\\OnlineDataBuilderServer\\OnlineDataBuilder\\Controllers\\WeatherForecastController.cs:line 43\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at SchoolInMindServer.MiddlewareServices.RequestMiddleware.Invoke(HttpContext context, CurrentSession currentSession) in D:\\ws\\Server\\OnlineDataBuilderServer\\OnlineDataBuilder\\MiddlewareServices\\RequestMiddleware.cs:line 65\r\n   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)\r\n   at SchoolInMindServer.MiddlewareServices.ExceptionHandlerMiddleware.Invoke(HttpContext context, ApplicationConfiguration applicationConfiguration) in D:\\ws\\Server\\OnlineDataBuilderServer\\OnlineDataBuilder\\MiddlewareServices\\ExceptionHandlerMiddleware.cs:line 28"},"HttpStatusCode":500,"HttpStatusMessage":"An item with the same key has already been added. Key: _EmailSettingDetailId","AuthenticationToken":""}